{% set name = "djongo5" %}
{% set version = "1.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/djongo5-{{ version }}.tar.gz
  sha256: b593931d5b712d90ef7bb42b6b4cbdc404e3db37e665264cbe7e56121474e268

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - sqlparse >=0.2.4
    - pymongo >=3.2.0
    - django >=2.1
    - pytz >=2018.5

test:
  imports:
    - djongo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.djongomapper.com/
  dev_url: https://github.com/minasielemma/djongo5-1.3.10
  summary: Driver for allowing Django 5 to use MongoDB as the database backend.
  license: AGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
